version: "2.4"
networks:
    scrapyd_service_net:
services:
  scrapyd_service_master:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: master
    environment:
      - identity=master
      - node=master
      - slaves=["127.0.0.1:6801","127.0.0.1:6802"]
      - codepath=/app/spider/DataCrawl
      - branch=develop
    networks:
      - scrapyd_service_net
    ports:
      - "6800:6800"
    volumes:
      - ./DataCrawl:/app/spider/DataCrawl
      - ./scrapyd_service:/app/source/scrapyd_service
      - ./logs/master:/app/source/logs
    restart: always
  scrapyd_service_slave_1:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: slave001
    environment:
      - identity=slave
      - node=slave001
      - slaves=[]
      - codepath=/app/spider/DataCrawl
      - branch=develop
    networks:
      - scrapyd_service_net
    ports:
      - "6801:6800"
    volumes:
      - ./DataCrawl:/app/spider/DataCrawl
      - ./scrapyd_service:/app/source/scrapyd_service
      - ./logs/slave001:/app/source/logs
    restart: always
  scrapyd_service_slave_2:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: slave002
    environment:
      - identity=slave
      - node=slave002
      - slaves=[]
      - codepath=/app/spider/DataCrawl
      - branch=develop
    networks:
      - scrapyd_service_net
    ports:
      - "6802:6800"
    volumes:
      - ./DataCrawl:/app/spider/DataCrawl
      - ./scrapyd_service:/app/source/scrapyd_service   
      - ./logs/slave002:/app/source/logs
    restart: always
  